import { Component, computed, effect, inject, linkedSignal, signal, SimpleChange, untracked } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { SimpleScoreLineComponent } from '../simple-score-line/simple-score-line.component';
import { ScoreLineComponent } from '../score-line/score-line.component';
import { Course, GolfCourse, GolfRound, GolfTeam, HoleData, PlayerInfo, StatTotal, TeamHoleScore, TeeBox } from '../../models/golf-course';
import { catchError, EMPTY, tap, finalize, Observable, switchMap, take, debounceTime } from 'rxjs';
import { rxResource, takeUntilDestroyed, toObservable, toSignal } from '@angular/core/rxjs-interop';
import { GolfCourseService } from '../../services/golf-course.service';
import { TeamManager} from '../../team-manager/team-manager';
import { UserProfile, UserProfileService } from 'shared-data';
import { checkHandicapHole } from '../../utils/score-utils';
import { TeamBalancerService } from '../../services/team-balancer.service';


@Component({
  selector: 'app-scorecard',
  standalone: true,
  imports: [CommonModule, SimpleScoreLineComponent, ScoreLineComponent, TeamManager],
  templateUrl: './scorecard.html',
  styleUrl: './scorecard.scss',
})
export class Scorecard {


  private golfCourseService = inject(GolfCourseService);
  public userProfileService = inject(UserProfileService);
  public teamBalanceerService = inject(TeamBalancerService);

  //UI State
  showTeamManager = signal(false); // add toggle state

  //PlayerInfo
  public currentPlayer = computed(() => this.userProfileService.userProfile() ?? {});


  playerList: Partial<PlayerInfo>[] = [];

  // 1. Course Info
  courseName = signal('Loading Course...');
  playDate = signal(new Date());
  isLoading = signal(true);
  selectedCourseId = signal('golf-course-nutcracker');
  addingPlayer = false;
  // players

  // Holds the full course data
  // Initialize with a partial object cast to GolfCourse to satisfy TS initially,
  // or better yet, handle the loading state in the template.

  golfCourseData = signal<GolfCourse>({} as GolfCourse);
  course = signal<Course>({} as Course);

  // 2. Mode Switching
  isDetailedMode = signal(false);
  scoreType = signal<'net' | 'gross'>('gross');


  // 3. Tees
  // Initialize with empty holeinfo to be safe until data loads
  currentTees = signal<TeeBox>({holeinfo: []} as unknown as TeeBox);

  // 4. Players State (The Master List)
  rounds = signal<GolfRound[]>([]);
  // Teams generated by the Team Manager
  generatedTeams = signal<GolfTeam[]>([]);

  // Computed Signal: Automatically recalculates whenever 'generatedTeams' OR 'rounds' changes.
  scoredTeams = computed(() => {
    const teams = this.generatedTeams();
    const rounds = this.rounds();
    const tees = this.currentTees();
    return this.calculateTeamScores(teams, rounds, tees, 2, 'match');
  });

  constructor() {
    console.log('Scorecard Component Initialized!');
    this.golfCourseService.getPlayerList()
      .pipe(
        catchError((error) => {
          console.error('Error loading player data:', error);
          return EMPTY;
        })
      )
      .subscribe(data => {
        this.playerList = data;
      });
    

    // this.loadCourseData();

    this.golfCourseService.totalCounter.subscribe(data => {
      this.rounds.update(currentRounds => {
        if (currentRounds.length > 0 && data.length > 0) {
             currentRounds[0].summary_score = data[0];
        }
        return currentRounds;
      });
    });
      // EFFECT A: Initialize with User Profile
  effect(() => {
    const user = this.userProfileService.userProfile();

    // Only initialize if we have a user AND the list is currently empty
    // untracked() ensures we don't re-run if 'rounds' changes later
    if (user && untracked(() => this.rounds().length === 0)) {

      const initialRound: GolfRound = {
        id: user.uid ?? new Date().getTime().toString(),
        golfer: {
          email: user.email ?? '',
          password: '',
          displayName: user.displayName ?? '',
          photoURL: '',
          emailVerified: true,
          playerInfo: {
            name: user.displayName ?? '',
            handicap: user.handicap ?? 0
          }
        },
        teeBox: {} as TeeBox, // Will be updated by the next effect
        round_date: new Date(),
        player_score: this.createEmptyRound(), // Creates initial structure
        summary_score: { totalScore: 0 }
      };

      this.rounds.set([initialRound]);
    }
  }, { allowSignalWrites: true });

    // EFFECT B: Update Rounds when Tees Change
  effect(() => {
    const tees = this.currentTees();

    // Guard: Make sure we have valid tee info
    if (!tees || !tees.holeinfo || tees.holeinfo.length === 0) return;

    // Use untracked to read 'rounds' so we don't create an infinite loop
    // (We want to write to rounds, not react to rounds changing)
    untracked(() => {
      this.rounds.update(currentRounds => {
        return currentRounds.map(round => {
          // 1. Update the TeeBox info on the round itself
          const updatedRound = { ...round, teeBox: tees };

          // 2. Update the handicap/par for each hole in the score
          updatedRound.player_score = round.player_score.map((holeStat, index) => {
            const holeData = tees.holeinfo[index];
            return {
              ...holeStat,
              handicap: holeData?.hcap, // Update Hole Handicap
              // You could also update par here if you stored it on the stat
            };
          });

          return updatedRound;
        });
      });
    });
  }, { allowSignalWrites: true });

    // EFFECT C Sync Generated Teams to Rounds
    // If a team is generated with players not in the scorecard, add them.
    effect(() => {
      const teams = this.generatedTeams();
      const tees = this.currentTees();

      untracked(() => {
        this.rounds.update(currentRounds => {
          const updatedRounds = [...currentRounds];
          let changed = false;

          teams.forEach(team => {
            team.roster.forEach(member => {
              // Check if this member is already in rounds (Match by ID or Name)
              const match = updatedRounds.find(r =>
                r.id === member.id ||
                r.golfer.playerInfo?.name === member.golfer.playerInfo?.name
              );

              if (!match) {
                const newRound = { ...member };
                // Apply Tee Info if available to ensure handicaps are present
                if (tees && tees.holeinfo) {
                  newRound.teeBox = tees;
                  newRound.player_score = newRound.player_score.map((stat, index) => ({
                    ...stat,
                    holeHandicap: tees.holeinfo[index]?.hcap
                  }));
                }
                updatedRounds.push(newRound);
                changed = true;
              }
            });
          });

          return changed ? updatedRounds : currentRounds;
        });
      });
    }, { allowSignalWrites: true });

    // LISTENER: Persistence (Debounced)
    toObservable(this.rounds)
      .pipe(
        debounceTime(2000), // Wait 2 seconds after last change
        tap(rounds => {
          console.log('💾 Auto-Save Triggered (Debounced):', rounds);
          // this.scoreService.saveRounds(rounds);
        })
      )
      .subscribe();
  }


  getCourseResourceSignalMethod = toSignal(
    toObservable(this.selectedCourseId)
      .pipe(
        tap( ()=> this.isLoading.set(true)),
        switchMap( id=> this.golfCourseService.getGolfCourse(id)),
        tap( (data: GolfCourse) => {
          if( data && data.course && data.course.tees[0]){
            this.currentTees.set(data.course.tees[0]);
            this.golfCourseData.set(data);
            this.courseName.set(data.course.name);
          }
           this.isLoading.set(false);
        }),
        catchError(err => {
          console.error('Failed to load course data', err);
          this.courseName.set('Error Loading Page'); // Correct string value
          this.isLoading.set(false)
          return EMPTY;
        })
      )
  )

  getCourseResouceSignalMethod_BAd = toSignal(
    toObservable(this.selectedCourseId)
      .pipe(
        tap(() => this.isLoading.set(true)),
        switchMap( id =>this.golfCourseService.getGolfCourse(id)),
        tap((data: GolfCourse) => {
            if (data && data.course && data.course.tees[0]) {
              this.currentTees.set(data.course.tees[0]);
              this.golfCourseData.set(data);
              this.courseName.set(data.course.name);
            }
            this.isLoading.set(false);
          })
      )
    );
  private calculateTeamScores(teams: GolfTeam[], rounds: GolfRound[], tees: TeeBox, bestBallCount: number, gameType: 'match' | 'stroke' = 'match'): GolfTeam[] {
    // 1. Calculate Best Ball Score for EACH team independently
    const calculatedTeams = teams.map( team => {
      // Sync Roster with latest scores
      // We do this because TeamManager creates *new* round instances (placeholders).
      // We need to swap those placeholders with the 'live' rounds from this.rounds()
      // so that we can see the actual scores and calculate the winner.
      const updatedRoster = team.roster.map( member => {
        const roundById = rounds.find(r => r.id === member.id);
        if(roundById) return roundById;

        // Fallback: Match by Name (since TeamManager generates new IDs)
        return rounds.find(r => r.golfer.playerInfo?.name === member.golfer.playerInfo?.name) || member;
      });

      const holeScores: TeamHoleScore[] = [];
      let totalNet = 0;
      let totalGross = 0;

      for (let i= 0; i < 18; i++ ) {
        const par = tees.holeinfo?.[i]?.par || 4;

        // Check if at least one player on the team has a score for this hole
        const teamHasStartedHole = updatedRoster.some(r => (Number(r.player_score[i]?.totalScore) || 0) > 0);

        // Get all net scores for this hole from the roster
        const holeResult = updatedRoster.map(r => {
          const stat = r.player_score[i];
          const gross = Number(stat?.totalScore) || 0;

          // if no score entered, return high number to ignore
          if (gross === 0) {
            if (teamHasStartedHole) {
              // Max Score: Net Double Bogey (Par + 2)
              return { net: par + 2, gross: par + 2 };
            }
            return {net: 999, gross: 999};
          }

          // Calculate net (gross - pops)
          const playerHcap = r.golfer?.playerInfo?.handicap || 0;
          const holeHcap = stat?.holeHandicap ?? 0;

          // Use utility function (returns boolean)
          const getsPop = checkHandicapHole(holeHcap, playerHcap);
          const pops = getsPop ? 1 : 0;

          return {net: gross - pops, gross: gross};
        });

        // sort by net score
        holeResult.sort((a, b) => a.net - b.net);

        // Take the best N balls
        const bestBalls = holeResult.slice(0, bestBallCount);

        // If the team hasn't started the hole, the score is 0 (unplayed)
        // If they have started, any missing scores were converted to Max Score above, so we can safely sum.
        const net = !teamHasStartedHole ? 0 : bestBalls.reduce((sum, r) => sum + r.net, 0);
        const gross = !teamHasStartedHole ? 0 : bestBalls.reduce((sum, r) => sum + r.gross, 0);

        totalNet += net;
        totalGross += gross;
        holeScores.push({holeNumber: i + 1, netScore: net, grossScore: gross, outcome: 'l'}); // Default to 'l' (loss) or undefined, updated below
      }

      return {
        ...team,
        roster: updatedRoster,
        score: {...team.score, netScore: totalNet, grossScore: totalGross, roundScore: holeScores}
      };
    });

    // 2. Match Play Comparison (if exactly 2 teams and mode is match)
    if( calculatedTeams.length === 2 && gameType === 'match') {
      const teamA = calculatedTeams[0];
      const teamB = calculatedTeams[1];

      for (let i = 0; i < 18; i++){
        const scoreA = teamA.score.roundScore[i].netScore;
        const scoreB = teamB.score.roundScore[i].netScore;

        // Ignore holes not played (assuming > 100 is invalid/placeholder)
        if( scoreA === 0 || scoreB === 0 || scoreA >= 100 || scoreB >= 100) continue;

        if(scoreA < scoreB) {
          teamA.score.roundScore[i].outcome = 'w';
          teamB.score.roundScore[i].outcome = 'l';
        } else if( scoreB < scoreA){
          teamB.score.roundScore[i].outcome = 'w';
          teamA.score.roundScore[i].outcome = 'l';
        }
        // Ties are ignored (outcome remains undefined)
      }
    }

    return calculatedTeams;
  }

 /* courseRXResource = rxResource({
    // 'request' tracks the signal. When selectedCourseId changes, the resource reloads.
    request: () => ({ id: this.selectedCourseId() }),

    // 'loader' performs the actual work
    loader: ({ request }) => this.golfCourseService.getGolfCourse(request.id)
  });

  courseName = computed(() => this.courseRXResource.value()?.course.name ?? 'Loading...');
  isLoading= computed(() => this.courseRXResource.isLoading());

  loadCourseData(targetGolfCourse: string = 'golf-course-nutcracker'){
    // The service handles the HTTP call now
    this.golfCourseService.getGolfCourse(targetGolfCourse)
      .pipe(
        take(1),
        tap((data: GolfCourse) => {
         if(data && data.course && data.course.tees){
            const teeList = data.course.tees;
            // Default to first tee
            this.currentTees.set(teeList[0]);
            this.golfCourseData.set(data);
            this.courseName.set(data.course.name);
           }
        }),
        catchError(err => {
          console.error('Failed to load course data', err);
          this.courseName.set('Error loading course');
          return EMPTY;
        }),
        finalize(() => this.isLoading.set(false))
      )
      .subscribe();
  }

  */

  selectTeeBox(tee: TeeBox) {
    this.currentTees.set(tee);

    // Update the rounds with the new tee box info
    this.rounds.update(currentRounds => {
        return currentRounds.map(round => ({
            ...round,
            teeBox: {
                color: tee.color,
                par: tee.par,
                slope: tee.slope,
                type: tee.type
            }
        }));
    });
  }

  onTeeChange(event: Event) {
    const select = event.target as HTMLSelectElement;
    const index = parseInt(select.value, 10);
    const tees = this.golfCourseData().course?.tees;
    if (tees && tees[index]) {
      this.selectTeeBox(tees[index]);
    }
  }

  isSelectedTee(tee: TeeBox): string {
    return this.currentTees().color === tee.color ? 'active' : '';
  }

  toggleMode(){
    this.isDetailedMode.update(v => !v);
  }

  addPlayer(selection: Event) {
    const target = selection?.target as HTMLSelectElement;
    const selectedPlayer = this.playerList.filter( p => p.name === target.value)[0];

    this.rounds.update(currentRounds => {
      const newPlayerNum = currentRounds.length + 1;
      const newRound: GolfRound = {
        id: Math.random().toString(36).substring(2, 9),
        golfer: {
          email: `${selectedPlayer.name}@example.com`,
          password: '',
          displayName: `${selectedPlayer.name}`,
          photoURL: '',
          emailVerified: false,
          playerInfo: { name: `${selectedPlayer.name}`, handicap: selectedPlayer.handicap}
        },
        teeBox: {},
        round_date: new Date(),
        player_score: this.createEmptyRound(),
        summary_score: { totalScore: 0 }
      };

      return [...currentRounds, newRound];
    });
  }

  updateScore(roundId: string, newScores: Partial<StatTotal>[]) {
    this.rounds.update(current =>
      current.map(r => r.id === roundId ? { ...r, player_score: newScores as StatTotal[] } : r)
    );
  }

  getTotalPar(start: number = 0, end: number = 18): number {
    return this.currentTees().holeinfo?.slice(start, end).reduce((sum, h) => sum + (h.par || 0), 0) || 0;
  }

  getTotalDistance(start: number = 0, end: number = 18): number {
    return this.currentTees().holeinfo?.slice(start, end).reduce((sum, h) => sum + (h.distance || 0), 0) || 0;
  }

  getTeeTotalDistance(tee: TeeBox): string {
      if (!tee || !tee.extra) return '-';
      const parts = tee.extra.split(' ');
      return parts.length > 0 ? parts[0] : '-';
  }

  private createEmptyRound(): StatTotal[] {
      let scoreArray:any = [];
      for (let i = 0; i < 18; i ++){
        let hole =
          {
            holeNumber: i+1,
            handicap: this.getHoleHandicap( i ),
            totalScore: 0,
            teeShots: undefined,
            fairwayStrokes: undefined,
            totalPutts: undefined,
            totalChips: undefined,
            penaltyStrokes: undefined,
            driveInFairway: undefined,
            greenInRegulation: undefined
          };
      scoreArray.push(hole);
    }

    console.log('createEmptyRound', scoreArray);
    return scoreArray;
  }

  toggleScoreType(){
    this.scoreType.update(current => current === 'gross' ? 'net' : 'gross');
  }

  getHoleHandicap(holeNumber: number){
     const hcap = this.currentTees()?.holeinfo?.[holeNumber]?.hcap;
     return hcap;
  }

  getGolfCourse(event: Event){
    const target = event.target as HTMLInputElement;
    this.golfCourseService.getGolfCourse(target.value);
  }

  isHandicapHole(handicap: number): string{
    // we will compare the user's handicap and determine if they get a stroke(s) on the hole
    const hCap = this.userProfileService.userProfile()?.handicap ?? 0;
    const getsAPop = checkHandicapHole(handicap, hCap);
    return  !getsAPop ? 'disabled' : '';
  }

  getRoundInfo(){
    console.log('this.rounds ', this.rounds());
    console.log('this.teams ', this.generatedTeams())
  }

}
