import { Component, computed, effect, inject, linkedSignal, signal, SimpleChange, untracked } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SimpleScoreLineComponent } from '../simple-score-line/simple-score-line.component';
import { ScoreLineComponent } from '../score-line/score-line.component';
import { Course, GolfCourse, GolfRound, HoleData, PlayerInfo, StatTotal, TeeBox } from '../../models/golf-course';
import { catchError, EMPTY, tap, finalize, Observable, switchMap, take } from 'rxjs';
import { rxResource, takeUntilDestroyed, toObservable, toSignal } from '@angular/core/rxjs-interop';
import { GolfCourseService } from '../../services/golf-course.service';
import { TeamManager} from '../../team-manager/team-manager';
import { UserProfile, UserProfileService } from 'shared-data';
import { checkHandicapHole } from '../../utils/score-utils';


@Component({
  selector: 'app-scorecard',
  standalone: true,
  imports: [CommonModule, SimpleScoreLineComponent, ScoreLineComponent, TeamManager],
  templateUrl: './scorecard.html',
  styleUrl: './scorecard.scss',
})
export class Scorecard {


  private golfCourseService = inject(GolfCourseService);
  public userProfileService = inject(UserProfileService);

  //UI State
  showTeamManager = signal(false); // add toggle state

  //PlayerInfo
  public currentPlayer = computed(() => this.userProfileService.userProfile() ?? {});


  readonly playerList: Partial<PlayerInfo>[] = [
    { name: 'John Jaeckle Sr', handicap: 16 },
    { name: 'John Jaeckle Jr,', handicap: 13 },
    { name: 'Larry Swift', handicap: 10 },
    { name: 'Jim Bryan', handicap: 4 },
    { name: 'Ralph ', handicap: 11 },
    { name: 'Carmine', handicap: 8 },
    { name: 'Jim Dodson', handicap: 13 },
    { name: 'Paul Bueme', handicap: 8 },
    { name: 'Frank Andrews', handicap: 8 },
  ];

  // 1. Course Info
  courseName = signal('Loading Course...');
  playDate = signal(new Date());
  isLoading = signal(true);
  selectedCourseId = signal('golf-course-nutcracker');
  addingPlayer = false;
  // players

  // Holds the full course data
  // Initialize with a partial object cast to GolfCourse to satisfy TS initially,
  // or better yet, handle the loading state in the template.

  golfCourseData = signal<GolfCourse>({} as GolfCourse);
  course = signal<Course>({} as Course);

  // 2. Mode Switching
  isDetailedMode = signal(false);

  // 3. Tees
  // Initialize with empty holeinfo to be safe until data loads
  currentTees = signal<TeeBox>({holeinfo: []} as unknown as TeeBox);

  // 4. Players State (The Master List)
  rounds = signal<GolfRound[]>([]);
  // Teams generated by the Team Manager
  generatedTeams = signal<Partial<PlayerInfo>[][]>([]);

  constructor() {
    console.log('Scorecard Component Initialized!');
    // this.loadCourseData();

    this.golfCourseService.totalCounter.subscribe(data => {
      this.rounds.update(currentRounds => {
        if (currentRounds.length > 0 && data.length > 0) {
             currentRounds[0].summary_score = data[0];
        }
        return currentRounds;
      });
    });
      // EFFECT A: Initialize with User Profile
  effect(() => {
    const user = this.userProfileService.userProfile();

    // Only initialize if we have a user AND the list is currently empty
    // untracked() ensures we don't re-run if 'rounds' changes later
    if (user && untracked(() => this.rounds().length === 0)) {

      const initialRound: GolfRound = {
        id: user.uid ?? new Date().getTime().toString(),
        golfer: {
          email: user.email ?? '',
          password: '',
          displayName: user.displayName ?? '',
          photoURL: '',
          emailVerified: true,
          playerInfo: {
            name: user.displayName ?? '',
            handicap: user.handicap ?? 0
          }
        },
        teeBox: {} as TeeBox, // Will be updated by the next effect
        round_date: new Date(),
        player_score: this.createEmptyRound(), // Creates initial structure
        summary_score: { totalScore: 0 }
      };

      this.rounds.set([initialRound]);
    }
  }, { allowSignalWrites: true });

    // EFFECT B: Update Rounds when Tees Change
  effect(() => {
    const tees = this.currentTees();

    // Guard: Make sure we have valid tee info
    if (!tees || !tees.holeinfo || tees.holeinfo.length === 0) return;

    // Use untracked to read 'rounds' so we don't create an infinite loop
    // (We want to write to rounds, not react to rounds changing)
    untracked(() => {
      this.rounds.update(currentRounds => {
        return currentRounds.map(round => {
          // 1. Update the TeeBox info on the round itself
          const updatedRound = { ...round, teeBox: tees };

          // 2. Update the handicap/par for each hole in the score
          updatedRound.player_score = round.player_score.map((holeStat, index) => {
            const holeData = tees.holeinfo[index];
            return {
              ...holeStat,
              handicap: holeData?.hcap, // Update Hole Handicap
              // You could also update par here if you stored it on the stat
            };
          });

          return updatedRound;
        });
      });
    });
  }, { allowSignalWrites: true });
  }

  getCourseResourceSignalMethod = toSignal(
    toObservable(this.selectedCourseId)
      .pipe(
        tap( ()=> this.isLoading.set(true)),
        switchMap( id=> this.golfCourseService.getGolfCourse(id)),
        tap( (data: GolfCourse) => {
          if( data && data.course && data.course.tees[0]){
            this.currentTees.set(data.course.tees[0]);
            this.golfCourseData.set(data);
            this.courseName.set(data.course.name);
          }
           this.isLoading.set(false);
        }),
        catchError(err => {
          console.error('Failed to load course data', err);
          this.courseName.set('Error Loading Page'); // Correct string value
          this.isLoading.set(false)
          return EMPTY;
        })
      )
  )

  getCourseResouceSignalMethod_BAd = toSignal(
    toObservable(this.selectedCourseId)
      .pipe(
        tap(() => this.isLoading.set(true)),
        switchMap( id =>this.golfCourseService.getGolfCourse(id)),
        tap((data: GolfCourse) => {
            if (data && data.course && data.course.tees[0]) {
              this.currentTees.set(data.course.tees[0]);
              this.golfCourseData.set(data);
              this.courseName.set(data.course.name);
            }
            this.isLoading.set(false);
          })
      )
    );
 /* courseRXResource = rxResource({
    // 'request' tracks the signal. When selectedCourseId changes, the resource reloads.
    request: () => ({ id: this.selectedCourseId() }),

    // 'loader' performs the actual work
    loader: ({ request }) => this.golfCourseService.getGolfCourse(request.id)
  });

  courseName = computed(() => this.courseRXResource.value()?.course.name ?? 'Loading...');
  isLoading= computed(() => this.courseRXResource.isLoading());

  loadCourseData(targetGolfCourse: string = 'golf-course-nutcracker'){
    // The service handles the HTTP call now
    this.golfCourseService.getGolfCourse(targetGolfCourse)
      .pipe(
        take(1),
        tap((data: GolfCourse) => {
         if(data && data.course && data.course.tees){
            const teeList = data.course.tees;
            // Default to first tee
            this.currentTees.set(teeList[0]);
            this.golfCourseData.set(data);
            this.courseName.set(data.course.name);
           }
        }),
        catchError(err => {
          console.error('Failed to load course data', err);
          this.courseName.set('Error loading course');
          return EMPTY;
        }),
        finalize(() => this.isLoading.set(false))
      )
      .subscribe();
  }

  */

  selectTeeBox(tee: TeeBox) {
    this.currentTees.set(tee);

    // Update the rounds with the new tee box info
    this.rounds.update(currentRounds => {
        return currentRounds.map(round => ({
            ...round,
            teeBox: {
                color: tee.color,
                par: tee.par,
                slope: tee.slope,
                type: tee.type
            }
        }));
    });
  }

  isSelectedTee(tee: TeeBox): string {
    return this.currentTees().color === tee.color ? 'active' : '';
  }

  toggleMode(){
    this.isDetailedMode.update(v => !v);
  }

  addPlayer(selection: Event) {
    const target = selection?.target as HTMLSelectElement;
    const selectedPlayer = this.playerList.filter( p => p.name === target.value)[0];

    this.rounds.update(currentRounds => {
      const newPlayerNum = currentRounds.length + 1;
      const newRound: GolfRound = {
        id: Math.random().toString(36).substring(2, 9),
        golfer: {
          email: `${selectedPlayer.name}@example.com`,
          password: '',
          displayName: `${selectedPlayer.name}`,
          photoURL: '',
          emailVerified: false,
          playerInfo: { name: `${selectedPlayer.name}`, handicap: selectedPlayer.handicap}
        },
        teeBox: {},
        round_date: new Date(),
        player_score: this.createEmptyRound(),
        summary_score: { totalScore: 0 }
      };

      return [...currentRounds, newRound];
    });
  }

  getTotalPar(): number {
    return this.currentTees().holeinfo?.reduce((sum, h) => sum + (h.par || 0), 0) || 0;
  }

  getTotalDistance(): number {
    return this.currentTees().holeinfo?.reduce((sum, h) => sum + (h.distance || 0), 0) || 0;
  }

  getTeeTotalDistance(tee: TeeBox): string {
      if (!tee || !tee.extra) return '-';
      const parts = tee.extra.split(' ');
      return parts.length > 0 ? parts[0] : '-';
  }

  private createEmptyRound(): StatTotal[] {
      let scoreArray:any = [];
      for (let i = 0; i < 18; i ++){
        let hole =
          {
            holeNumber: i+1,
            handicap: this.getHoleHandicap( i ),
            totalScore: 0,
            teeShots: undefined,
            fairwayStrokes: undefined,
            totalPutts: undefined,
            totalChips: undefined,
            penaltyStrokes: undefined,
            driveInFairway: undefined,
            greenInRegulation: undefined
          };
      scoreArray.push(hole);
    }

    console.log('createEmptyRound', scoreArray);
    return scoreArray;
  }
  getHoleHandicap(holeNumber: number){
     const hcap = this.currentTees()?.holeinfo?.[holeNumber]?.hcap;
     return hcap;
  }

  getGolfCourse(event: Event){
    const target = event.target as HTMLInputElement;
    this.golfCourseService.getGolfCourse(target.value);
  }

  isHandicapHole(handicap: number): string{
    // we will compare the user's handicap and determine if they get a stroke(s) on the hole
    const hCap = this.userProfileService.userProfile()?.handicap ?? 0;
    const getsAPop = checkHandicapHole(handicap, hCap);
    return  !getsAPop ? 'disabled' : '';
  }

  getRoundInfo(){
    debugger;
    console.log('this.rounds ', this.rounds());
  }
}
