import {
  Component,
  computed,
  effect,
  EnvironmentInjector,
  inject,
  linkedSignal,
  signal,
  SimpleChange,
  untracked,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { SimpleScoreLineComponent } from '../simple-score-line/simple-score-line.component';
import { ScoreLineComponent } from '../score-line/score-line.component';
import { ScoreSummary } from '../score-summary/score-summary';
import { Course, GolfCourse, GolfRound, GolfTeam, HoleData, PlayerInfo, StatTotal, TeamHoleScore, TeeBox } from '../../models/golf-course';
import { catchError, EMPTY, tap, finalize, Observable, switchMap, take, debounceTime, map, of } from 'rxjs';
import { rxResource, takeUntilDestroyed, toObservable, toSignal } from '@angular/core/rxjs-interop';
import { GolfCourseService } from '../../services/golf-course.service';
import { TeamManager} from '../../team-manager/team-manager';
import { GameService } from '../../services/game-service';
import { UserProfile, UserProfileService } from 'shared-data';
import { checkHandicapHole } from '../../utils/score-utils';
import { TeamBalancerService } from '../../services/team-balancer.service';
import { loadRemoteModule } from '@angular-architects/native-federation';
import { ActivatedRoute } from '@angular/router';
import { subscribe } from '@angular/fire/data-connect';



@Component({
  selector: 'app-scorecard',
  standalone: true,
  imports: [CommonModule, SimpleScoreLineComponent, ScoreLineComponent, TeamManager, ScoreSummary],
  templateUrl: './scorecard.html',
  styleUrl: './scorecard.scss',
})
export class Scorecard {

  private aRoute = inject(ActivatedRoute);
  gameId = toSignal(this.aRoute.queryParams.pipe(map(p => p['gameId'] as string)));
  teamId = toSignal(this.aRoute.queryParams.pipe(map(p => p['teamId'] as string)));

  private gameService = inject(GameService);
  private golfCourseService = inject(GolfCourseService);

  public userProfileService = inject(UserProfileService);
  public teamBalanceerService = inject(TeamBalancerService);
  public teamManagerRemote = signal<any>(null);


  //UI State
  showTeamManager = signal(false); // add toggle state

  //PlayerInfo
  public currentPlayer = computed(() => this.userProfileService.userProfile() ?? {});


  playerList: Partial<PlayerInfo>[] = [];


  // 1. Course Info
  selectedCourseId = signal('golf-course-nutcracker');
  playDate = signal(new Date());
  addingPlayer = false;


  // 1. Fetch the team's rounds from Firestore once the IDs arrive


  public teamRoundsResource = rxResource({
     params: () => ({ gameId: this.gameId(), teamId: this.teamId() }),
     stream: ({ params }) => {
       if (!params.gameId || !params.teamId) return EMPTY;
       return this.gameService.getTeamRounds(params.gameId, params.teamId);
     }
   });

  public courseResource = rxResource({
    // 1. Rename 'request' to 'params'
    params: () => ({ id: this.selectedCourseId() }),

    // 2. Rename 'loader' to 'stream' (accepts the reactive params argument)
    stream: (ctx) => this.golfCourseService.getGolfCourse(ctx.params.id)
  });


  // Derived reactive states based on the course resource
  golfCourseData = computed(() => this.courseResource.value() ?? {} as GolfCourse);
  courseName = computed(() => {
    if (this.courseResource.error()) {
      return 'Error Loading Page';
    }
    return this.courseResource.value()?.course?.name ?? 'Loading Course...';
  });
  isLoading = computed(() => this.courseResource.isLoading());

  // 2. Mode Switching
  isDetailedMode = signal(false);
  scoreType = signal<'net' | 'gross'>('gross');


  // 3. Tees
  currentTees = linkedSignal({
    source: () => this.courseResource.value(),
    computation: (data) => data?.course?.tees?.[0] ?? { holeinfo: [] } as unknown as TeeBox
  });

  // 4. Players State (The Master List)
  rounds = linkedSignal({
    source: () => ({
      dbRounds: this.teamRoundsResource.value(),
      user: this.userProfileService.userProfile(),
      courseId: this.selectedCourseId()
    }),
    computation: (source) => {
      if (source.dbRounds && source.dbRounds.length > 0) return source.dbRounds;
      return source.user ? [this.createInitialRoundForUser(source.user)] : [];
    }
  });
  // Teams generated by the Team Manager
  generatedTeams = signal<GolfTeam[]>([]);

  // Computed Signal: Automatically recalculates whenever 'generatedTeams' OR 'rounds' changes.
  scoredTeams = computed(() => {
    const teams = this.generatedTeams();
    const rounds = this.rounds();
    const tees = this.currentTees();
    return this.calculateTeamScores(teams, rounds, tees, 2, 'match');
  });

  constructor() {

    effect(() => {
      const gId = this.gameId();
      const tId = this.teamId();

      if (gId && tId) {
        console.log('Triggering fetch for:', { gId, tId });
        this.gameService.getTeamRounds(gId, tId)
          .pipe(
            tap(rounds => console.log('Firestore Rounds found:', rounds)),
            catchError(err => {
              console.error('Fetch Error:', err);
              return EMPTY;
            })
          ).subscribe();
      }
    });
    effect(() => {
      console.group('🎮 Game Resource State Update');
      console.log('Status:', this.teamRoundsResource.status());
      console.log('Is Loading:', this.teamRoundsResource.isLoading());
      console.log('Value:', this.teamRoundsResource.value());
      console.log('Error:', this.teamRoundsResource.error());
      console.groupEnd();
    });

    this.golfCourseService.getPlayerList()
      .pipe(
        catchError((error) => {
          console.error('Error loading player data:', error);
          return EMPTY;
        })
      )
      .subscribe(data => {
        this.playerList = data;
      });


    // this.loadCourseData();

    this.golfCourseService.totalCounter.subscribe(data => {
      this.rounds.update(currentRounds => {
        if (currentRounds.length > 0 && data.length > 0) {
             currentRounds[0].summary_score = data[0];
        }
        return currentRounds;
      });
    });

      // EFFECT A: Sync Tee Changes to Rounds
    effect(() => {
      const tees = this.currentTees();
      if (!tees || !tees.holeinfo || tees.holeinfo.length === 0) return;

      // Use untracked to prevent a dependency loop
      untracked(() => {
        this.rounds.update(currentRounds => {
          return currentRounds.map(round => {
            const updatedRound = { ...round, teeBox: tees };
            updatedRound.player_score = round.player_score.map((holeStat, index) => ({
              ...holeStat,
              handicap: tees.holeinfo[index]?.hcap,
            }));
            return updatedRound;
          });
        });
      });
    });

    // EFFECT B: Sync Generated Teams to Rounds
    effect(() => {
      const teams = this.generatedTeams();
      const tees = this.currentTees(); // Needed to initialize new players with correct tee info

      untracked(() => {
        this.rounds.update(currentRounds => {
          const updatedRounds = [...currentRounds];
          let changed = false;

          teams.forEach(team => {
            team.roster.forEach(member => {
              const match = updatedRounds.find(r => r.id === member.id || r.golfer.playerInfo?.name === member.golfer.playerInfo?.name);

              if (!match) {
                const newRound = { ...member };
                if (tees && tees.holeinfo) {
                  newRound.teeBox = tees;
                  newRound.player_score = newRound.player_score.map((stat, index) => ({
                    ...stat,
                    handicap: tees.holeinfo[index]?.hcap,
                  }));
                }
                updatedRounds.push(newRound);
                changed = true;
              }
            });
          });
          // Only return a new array if a change actually occurred
          return changed ? updatedRounds : currentRounds;
        });
      });
    });

  }

  private createInitialRoundForUser(user: any): GolfRound {
    return {
      id: user.uid ?? new Date().getTime().toString(),
      golfer: {
        // We only need the display name and handicap for the scorecard.
        // All other user data is irrelevant to the round itself.
        displayName: user.displayName ?? 'New Golfer',
        playerInfo: {
          name: user.displayName ?? 'New Golfer',
          handicap: user.playerInfo?.handicap ?? user.handicap ?? 0,
        }
      },
      teeBox: {} as TeeBox,
      round_date: new Date(),
      player_score: this.createEmptyRound(),
      summary_score: { totalScore: 0 }
    };
  }


  loadRemoteManager(){
    loadRemoteModule('mfe-teamManager','./Component')
    .then((module: any) =>  {
      console.log('REMOTE MODULE DOWNLOADED:', module);
      console.log(' Is teammangerin module? ', !!module.TeamManager)
      if(module.TeamManager){
        this.teamManagerRemote.set(module.TeamManager);
      }else if (module.default) {
        this.teamManagerRemote.set(module.default);
      }else {
        console.error( 'TeamManager class not found in the loaded module')
      }
     })
      .catch(error => console.error('Error loading remote manager'))
  }

  private calculateTeamScores(teams: GolfTeam[], rounds: GolfRound[], tees: TeeBox, bestBallCount: number, gameType: 'match' | 'stroke' = 'match'): GolfTeam[] {
    // 1. Calculate Best Ball Score for EACH team independently
    const calculatedTeams = teams.map( team => {
      // Sync Roster with latest scores
      // We do this because TeamManager creates *new* round instances (placeholders).
      // We need to swap those placeholders with the 'live' rounds from this.rounds()
      // so that we can see the actual scores and calculate the winner.
      const updatedRoster = team.roster.map( member => {
        const roundById = rounds.find(r => r.id === member.id);
        if(roundById) return roundById;

        // Fallback: Match by Name (since TeamManager generates new IDs)
        return rounds.find(r => r.golfer.playerInfo?.name === member.golfer.playerInfo?.name) || member;
      });

      const holeScores: TeamHoleScore[] = [];
      let totalNet = 0;
      let totalGross = 0;

      for (let i= 0; i < 18; i++ ) {
        const par = tees.holeinfo?.[i]?.par || 4;

        // Check if at least one player on the team has a score for this hole
        const teamHasStartedHole = updatedRoster.some(r => (Number(r.player_score[i]?.totalScore) || 0) > 0);

        // Get all net scores for this hole from the roster
        const holeResult = updatedRoster.map(r => {
          const stat = r.player_score[i];
          const gross = Number(stat?.totalScore) || 0;

          // if no score entered, return high number to ignore
          if (gross === 0) {
            if (teamHasStartedHole) {
              // Max Score: Net Double Bogey (Par + 2)
              return { net: par + 2, gross: par + 2 };
            }
            return {net: 999, gross: 999};
          }

          // Calculate net (gross - pops)
          const playerHcap = r.golfer?.playerInfo?.handicap || 0;
          const holeHcap = stat?.holeHandicap ?? 0;

          // Use utility function (returns boolean)
          const getsPop = checkHandicapHole(holeHcap, playerHcap);
          const pops = getsPop ? 1 : 0;

          return {net: gross - pops, gross: gross};
        });

        // sort by net score
        holeResult.sort((a, b) => a.net - b.net);

        // Take the best N balls
        const bestBalls = holeResult.slice(0, bestBallCount);

        // If the team hasn't started the hole, the score is 0 (unplayed)
        // If they have started, any missing scores were converted to Max Score above, so we can safely sum.
        const net = !teamHasStartedHole ? 0 : bestBalls.reduce((sum, r) => sum + r.net, 0);
        const gross = !teamHasStartedHole ? 0 : bestBalls.reduce((sum, r) => sum + r.gross, 0);

        totalNet += net;
        totalGross += gross;
        holeScores.push({holeNumber: i + 1, netScore: net, grossScore: gross, outcome: 'l'}); // Default to 'l' (loss) or undefined, updated below
      }

      return {
        ...team,
        roster: updatedRoster,
        score: {...team.score, netScore: totalNet, grossScore: totalGross, roundScore: holeScores}
      };
    });

    // 2. Match Play Comparison (if exactly 2 teams and mode is match)
    if( calculatedTeams.length === 2 && gameType === 'match') {
      const teamA = calculatedTeams[0];
      const teamB = calculatedTeams[1];

      for (let i = 0; i < 18; i++){
        const scoreA = teamA.score.roundScore[i].netScore;
        const scoreB = teamB.score.roundScore[i].netScore;

        // Ignore holes not played (assuming > 100 is invalid/placeholder)
        if( scoreA === 0 || scoreB === 0 || scoreA >= 100 || scoreB >= 100) continue;

        if(scoreA < scoreB) {
          teamA.score.roundScore[i].outcome = 'w';
          teamB.score.roundScore[i].outcome = 'l';
        } else if( scoreB < scoreA){
          teamB.score.roundScore[i].outcome = 'w';
          teamA.score.roundScore[i].outcome = 'l';
        }
        // Ties are ignored (outcome remains undefined)
      }
    }

    return calculatedTeams;
  }

 /* courseRXResource = rxResource({
    // 'request' tracks the signal. When selectedCourseId changes, the resource reloads.
    request: () => ({ id: this.selectedCourseId() }),

    // 'loader' performs the actual work
    loader: ({ request }) => this.golfCourseService.getGolfCourse(request.id)
  });

  courseName = computed(() => this.courseRXResource.value()?.course.name ?? 'Loading...');
  isLoading= computed(() => this.courseRXResource.isLoading());

  loadCourseData(targetGolfCourse: string = 'golf-course-nutcracker'){
    // The service handles the HTTP call now
    this.golfCourseService.getGolfCourse(targetGolfCourse)
      .pipe(
        take(1),
        tap((data: GolfCourse) => {
         if(data && data.course && data.course.tees){
            const teeList = data.course.tees;
            // Default to first tee
            this.currentTees.set(teeList[0]);
            this.golfCourseData.set(data);
            this.courseName.set(data.course.name);
           }
        }),
        catchError(err => {
          console.error('Failed to load course data', err);
          this.courseName.set('Error loading course');
          return EMPTY;
        }),
        finalize(() => this.isLoading.set(false))
      )
      .subscribe();
  }

  */

  selectTeeBox(tee: TeeBox) {
    this.currentTees.set(tee);

    // Update the rounds with the new tee box info
    this.rounds.update(currentRounds => {
        return currentRounds.map(round => ({
            ...round,
            teeBox: {
                color: tee.color,
                par: tee.par,
                slope: tee.slope,
                type: tee.type
            }
        }));
    });
  }

  onTeeChange(event: Event) {
    const select = event.target as HTMLSelectElement;
    const index = parseInt(select.value, 10);
    const tees = this.golfCourseData().course?.tees;
    if (tees && tees[index]) {
      this.selectTeeBox(tees[index]);
    }
  }

  isSelectedTee(tee: TeeBox): string {
    return this.currentTees().color === tee.color ? 'active' : '';
  }

  toggleMode(){
    this.isDetailedMode.update(v => !v);
  }

  addPlayer(selection: Event) {
    const target = selection?.target as HTMLSelectElement;
    const selectedPlayer = this.playerList.filter( p => p.name === target.value)[0];

    this.rounds.update(currentRounds => {
      const newPlayerNum = currentRounds.length + 1;
      const newRound: GolfRound = {
        id: Math.random().toString(36).substring(2, 9),
        golfer: {
          email: `${selectedPlayer.name}@example.com`,
          password: '',
          displayName: `${selectedPlayer.name}`,
          photoURL: '',
          emailVerified: false,
          playerInfo: { name: `${selectedPlayer.name}`, handicap: selectedPlayer.handicap}
        },
        teeBox: {},
        round_date: new Date(),
        player_score: this.createEmptyRound(),
        summary_score: { totalScore: 0 }
      };

      return [...currentRounds, newRound];
    });
  }

  updateScore(roundId: string, newScores: Partial<StatTotal>[]) {
    this.rounds.update(current =>
      current.map(r => r.id === roundId ? { ...r, player_score: newScores as StatTotal[] } : r)
    );
  }

  getTotalPar(start: number = 0, end: number = 18): number {
    return this.currentTees().holeinfo?.slice(start, end).reduce((sum, h) => sum + (h.par || 0), 0) || 0;
  }

  getTotalDistance(start: number = 0, end: number = 18): number {
    return this.currentTees().holeinfo?.slice(start, end).reduce((sum, h) => sum + (h.distance || 0), 0) || 0;
  }

  getTeeTotalDistance(tee: TeeBox): string {
      if (!tee || !tee.extra) return '-';
      const parts = tee.extra.split(' ');
      return parts.length > 0 ? parts[0] : '-';
  }

  private createEmptyRound(): StatTotal[] {
      let scoreArray:any = [];
      for (let i = 0; i < 18; i ++){
        let hole =
          {
            holeNumber: i+1,
            handicap: this.getHoleHandicap( i ),
            totalScore: 0,
            teeShots: undefined,
            fairwayStrokes: undefined,
            totalPutts: undefined,
            totalChips: undefined,
            penaltyStrokes: undefined,
            driveInFairway: undefined,
            greenInRegulation: undefined
          };
      scoreArray.push(hole);
    }

    console.log('createEmptyRound', scoreArray);
    return scoreArray;
  }

  toggleScoreType(){
    this.scoreType.update(current => current === 'gross' ? 'net' : 'gross');
  }

  getHoleHandicap(holeNumber: number){
     const hcap = this.currentTees()?.holeinfo?.[holeNumber]?.hcap;
     return hcap;
  }

  getGolfCourse(event: Event){
    const target = event.target as HTMLInputElement;
    this.golfCourseService.getGolfCourse(target.value);
  }

  isHandicapHole(handicap: number): string{
    // we will compare the user's handicap and determine if they get a stroke(s) on the hole
    const hCap = this.userProfileService.userProfile()?.handicap ?? 0;
    const getsAPop = checkHandicapHole(handicap, hCap);
    return  !getsAPop ? 'disabled' : '';
  }

  getRoundInfo(){
    console.log('this.rounds ', this.rounds());
    console.log('this.teams ', this.generatedTeams())
  }

}
